function [fitresult, gof] = createFit(A, B, dA, dB)
%CREATEFIT(A,B)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : A
%      Y Output: B
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-May-2018 14:28:28


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( A, B );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData);
hold on
errorbar(A, B, dA, dB, '.');
%legend( h, 'B vs. A', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel A
ylabel B
grid on


