function [fitresult, gof] = createFit(B, U, dB, dU)
%CREATEFIT(B,U)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : B
%      Y Output: U
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-May-2018 17:47:08


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( B, U );

% Set up fittype and options.
ft = fittype( 'a*x+b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.957506835434298 0.964888535199277];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
hold on
errorbar(B, U, dB, dU, '.');
legend( h, 'U vs. B', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel B
ylabel U
grid on


